/**
 * Every word the interface says, in English and Turkish.
 *
 * One file rather than one per screen, because the thing that goes wrong with
 * translations is not writing them — it is noticing that one language has a key
 * the other does not. Side by side, a gap is visible; in two directories it is
 * not. `npm run check:strings` walks src/ and fails on a key that is used and
 * missing, or defined in one language only.
 *
 * **Interface, not content.** What a teacher types — activity titles, question
 * prompts, the AI prompt, rubric labels — is content and is never translated:
 * it is shown exactly as it was written, in whatever language it was written in.
 * The same goes for the tutor's replies and the marking summaries, which are
 * produced server-side against that authored content. A Turkish class working on
 * an activity a teacher wrote in Turkish sees Turkish throughout; the chrome
 * around it follows the language switch.
 *
 * Two conventions:
 *
 * - **`{name}` is a placeholder**, filled by the second argument to `t()`.
 *   Nothing else in a string is special.
 * - **`_one` / `_other`** are plural forms, chosen by `vars.count`. Turkish does
 *   not agree a noun with a numeral — "3 soru", not "3 sorular" — so both forms
 *   are usually the same sentence there. They are still both written out, so
 *   that reading down a key never leaves you wondering whether one was
 *   forgotten.
 *
 * Keys are nested for readability and flattened to `a.b.c` on load; see
 * ./i18n.jsx.
 */

const en = {
  app: {
    loading: 'Loading',
  },

  common: {
    loading: 'Loading…',
    saving: 'Saving…',
    cancel: 'Cancel',
    back: 'Back',
    remove: 'Remove',
    delete: 'Delete',
    optional: '(optional)',
    all: 'All',
    dismiss: 'Dismiss',
    questions_one: '{count} question',
    questions_other: '{count} questions',
    words_one: '{count} word',
    words_other: '{count} words',
    strokes_one: '{count} stroke',
    strokes_other: '{count} strokes',
    files_one: '{count} file',
    files_other: '{count} files',
    events_one: '{count} event',
    events_other: '{count} events',
    criteria_one: '{count} criterion',
    criteria_other: '{count} criteria',
  },

  /** The buttons that are on every screen. See components/TopBar.jsx. */
  nav: {
    label: 'Where to go',
    home: 'Home',
    signIn: 'Sign in',
    signOut: 'Sign out',
    signingOut: 'Signing out…',
    myConsole: 'My console',
    studentView: 'Student view',
    joinWithCode: 'Class code',
    language: 'Language',
    signedInAs: 'Signed in as {name}',
    working: 'Working anonymously',
  },

  topics: {
    label: 'Topic',
    all: 'All topics',
    none: 'No topic',
    unset: '— no topic —',
    ratio: 'Ratio',
    'whole-numbers': 'Whole numbers',
  },

  signin: {
    eyebrow: 'Staff and students with an account',
    title: 'Sign in',
    email: 'Email',
    password: 'Password',
    submit: 'Sign in',
    busy: 'Signing in…',
    noAccount: 'No account? Students join with a code from their teacher, or pick from the list.',
    startHere: 'Start as a student',
    staffAccounts: 'Teacher accounts are created by an administrator.',
  },

  entry: {
    step: 'Step {current} of {total}',

    consent: {
      eyebrow: 'Consent',
      title: 'Before you start',
      lede: 'This workspace is part of a research study on how AI feedback helps students work through problems. Please read this before you start.',
      recordedHead: 'What gets recorded',
      recorded1: 'Everything you type to the tutor, and everything it replies.',
      recorded2: 'Your answers — typed, drawn or uploaded — and the marks on them.',
      recorded3: 'Which questions you open, how you mark them, and when.',
      usedHead: 'How it is used',
      used1: 'To build an anonymous dataset for research on AI feedback in teaching.',
      used2: 'Your teacher may read your conversations and label them for the study.',
      used3: 'You are not asked for your name, your email or your school.',
      warn: 'Do not type your name, anyone else’s name, or any other personal detail into the workspace. You can stop at any time, and delete everything you did, from inside the workspace.',
      agree: 'I have read this, and I agree to my answers and conversations being recorded for this research.',
      continue: 'Agree and continue',
      decline: 'I do not agree',
    },

    declined: {
      eyebrow: 'Not started',
      title: 'Nothing has been recorded',
      lede: 'The workspace only runs with consent, so there is nothing further to do here. You can close this tab.',
      back: 'Back to the consent form',
    },

    who: {
      title: 'How are you working today?',
      lede: 'Either is fine. Anonymous is the normal way in — you only need an account if your teacher set one up for you.',
      anon: 'Continue anonymously',
      anonMeta: 'No account. Nothing is asked for.',
      signIn: 'Sign in',
      signInMeta: 'If your teacher gave you an email and password.',
    },

    pick: {
      title: 'What are you working on?',
      ledeSignedIn: 'Set by your teacher, and saved to your account.',
      ledeAnon: 'Pick the one your teacher told you to open. You are working anonymously.',
      signedInAs: 'Signed in as {name}. Everything you do is saved to your account.',
      empty: 'Nothing is open yet. Your teacher has to publish an activity before it appears here.',
      noneInTopic: 'Nothing open on that topic. Try another one, or All.',
      enterCode: 'Enter a class code',
    },

    /**
     * Shown to a teacher, manager or admin, in place of the consent form.
     * See routes/sessions.js on why they are not asked to agree to it.
     */
    staff: {
      eyebrow: 'Staff preview',
      notice: 'You are signed in as {role}, so the research consent notice does not apply to you. Anything you start here is recorded as a preview rather than as a student’s work.',
    },
  },

  join: {
    eyebrow: 'Class code',
    title: 'Join with a class code',
    lede: 'Six characters, from your teacher. Letters and numbers, and it does not matter whether you type them in capitals.',
    label: 'Class code',
    placeholder: 'ABC234',
    submit: 'Find the activity',
    busy: 'Looking…',
    found: 'Your teacher set this',
    start: 'Start this activity',
    starting: 'Starting…',
    another: 'Try a different code',
    orList: 'Or pick from the list instead',
  },

  ws: {
    loading: 'Loading your work',
    cannotOpen: 'Cannot open this session',
    startAgain: 'Start again',
    questionsFallback: 'Your questions',
    ownQuestions: 'Your own questions',
    markedLine: 'Marked {code} — {earned} of {total}.',
    fullMarks: 'Full marks.',
    handMarked: '{code} is with your teacher to mark by hand. I cannot score a drawing or a photo.',
    confirmWithdraw: 'Delete everything from this session? This cannot be undone.',
    tabQuestions: 'Questions',
    tabProblem: 'Problem',
    tabTutor: 'Tutor',
    showQuestions: 'Show questions',
    showTutor: 'Show tutor',
    showTutorUnread: 'Show tutor, new reply waiting',
    newReply: 'New reply',
    switchPanel: 'Switch panel',
    questionSet: 'Question set',
    tutorPane: 'AI tutor',
    closeTutor: 'Close tutor',
  },

  ql: {
    hide: 'Hide questions',
    tally: '{done} of {total}',
    tallyLabel: 'marked done',
    withTeacher: 'With your teacher',
    markedScore: '{mark} · {earned}/{total}',
    pictureQuestion: 'Question as a picture',
    askOwn: 'Ask your own',
    ownLabel: 'Your own question',
    ownPlaceholder: 'Stuck on something else? Type that question here and work on it with the tutor.',
    ownAdd: 'Add to my list',
    points: '{count} pts',
    withdraw: 'Delete everything I did',
  },

  qp: {
    marks: '{count} marks',
    questionOf: 'Question {current} of {total}',
    tutor: 'Tutor',
    questionAsSet: 'The question, as set',
    question: 'The question',
    yourAnswer: 'Your answer',
    howToAnswer: 'How to answer',
    modeWarn: 'Switching to {mode} discards {what}.',
    discardSwitch: 'Discard and switch',
    keepAnswer: 'Keep my answer',
    writtenAnswer: 'Your written answer',
    placeholderMarkable: 'Write your answer here. The tutor marks it against the rubric, not against a model answer.',
    placeholderUnmarked: 'Write what you have tried so far, and the tutor will work through it with you.',
    workingNudge: 'This one is normally worked out by hand — Draw or Upload usually suits it better.',
    boardAlt: 'Your whiteboard so far',
    editBoard: 'Edit your whiteboard',
    drawBoard: 'Draw on the whiteboard',
    boardMeta: '{strokes} · saved as {size}',
    boardHint: 'Squared paper · pen, eraser, undo',
    aPng: 'a PNG',
    addFile: 'Add a photo or a file',
    addFileMeta: 'Drop one here or paste it · JPG, PNG or PDF · 10 MB',
    rejected: 'Not added: {list}. Fix the file and attach it again.',
    openInTab: 'Open {name} in a new tab',
    check: 'Check my answer',
    hint: 'Get a hint',
    stale: 'Edited since it was marked — check again.',
    howDidItGo: 'How did this one go?',
    withTeacher: 'With your teacher',
    nothingToMark: 'Nothing to mark',
    doThisNext: 'Do this next',
    previous: 'Previous',
    next: 'Next',
    discardWrite_one: 'your typed answer ({count} word)',
    discardWrite_other: 'your typed answer ({count} words)',
    discardDraw_one: 'your whiteboard ({count} stroke)',
    discardDraw_other: 'your whiteboard ({count} strokes)',
    discardUpload_one: '{count} uploaded file',
    discardUpload_other: '{count} uploaded files',
  },

  tp: {
    tutor: 'Tutor',
    workingOn: 'Working on',
    hide: 'Hide tutor',
    close: 'Close',
    hintAction: 'Give me a hint',
    conceptAction: 'Explain the concept',
    exampleAction: 'Worked example',
    reviewAction: 'Check my reasoning',
    helpful: 'Marked helpful',
    notHelpful: 'Marked not helpful',
    didThisHelp: 'Did this help?',
    yes: 'Yes',
    no: 'No',
    writing: 'The tutor is writing',
    messageLabel: 'Message the tutor',
    placeholder: 'Ask about this question…',
    send: 'Send',
  },

  wb: {
    title: 'Whiteboard',
    forQuestion: 'Whiteboard for {code}',
    workingOn: 'Working on',
    penColour: 'Pen colour',
    erase: 'Erase',
    undo: 'Undo',
    clear: 'Clear',
    rotate: 'Turn your phone sideways for more room to write.',
    canvasLabel: 'Drawing area. Keyboard drawing is not supported — attach a photo of your working instead.',
    strokesSaved: '{strokes} · saves as a PNG with your answer',
    drawHint: 'Draw with a mouse, a finger or a stylus',
    save: 'Save to answer',
    inkGraphite: 'Graphite',
    inkTeal: 'Teal pen',
    inkRed: 'Red pen',
  },

  marks: {
    newLabel: 'Not started',
    newShort: 'New',
    draftLabel: 'Drafted, not checked',
    draftShort: 'Drafted',
    reviseLabel: 'Needs revision',
    reviseShort: 'Revise',
    masteredLabel: 'Mastered',
    masteredShort: 'Mastered',
    doneLabel: 'Done',
    doneShort: 'Done',
    unfinishedLabel: 'Not finished',
    unfinishedShort: 'Unfinished',
    wrongLabel: 'Got it wrong',
    wrongShort: 'Wrong',
  },

  modes: {
    writeLabel: 'Write',
    writeHint: 'Type your answer',
    drawLabel: 'Draw',
    drawHint: 'Whiteboard',
    uploadLabel: 'Upload',
    uploadHint: 'Photo or PDF',
  },

  teacher: {
    eyebrow: 'Teacher',
    sections: 'Teacher sections',
    activities: 'Activities',
    studentWork: 'Student work',
    labelling: 'Labelling',
    prompt: 'AI prompt',
    accounts: 'Accounts →',
  },

  activities: {
    eyebrow: 'Authoring',
    title: 'Activities',
    lede: 'An activity is a set of questions. Publishing it is what puts it in front of students — they open the site or type its class code, agree to the consent notice, and start. Everything they say to the tutor is recorded against it.',
    new: 'New activity',
    titleLabel: 'Title',
    titlePlaceholder: 'Sharing a bill three ways',
    blurbLabel: 'Blurb',
    blurbPlaceholder: 'Splitting quantities in a given ratio, and checking the total.',
    create: 'Create activity',
    creating: 'Creating…',
    scopeAll: 'Everything in the system',
    scopeOwn: 'Yours',
    empty: 'Nothing yet. Create an activity above, add a question or two, then publish it so students can see it.',
    noneInTopic: 'Nothing on that topic yet.',
    open: 'Open',
    draft: 'Draft',
    filterLabel: 'Filter by topic',
  },

  editor: {
    breadcrumb: 'Activities',
    seeWork: 'See their work',
    publish: 'Publish',
    closeToStudents: 'Close to students',
    openHead: 'Open to students',
    openHint: 'It appears in the list students see when they open the site, and its class code works. Publishing is what opens it, so close it again when the lesson is over.',
    draftHead: 'Not open yet',
    draftHintEmpty: 'Students cannot see this. Add at least one question, then publish it.',
    draftHint: 'Students cannot see this yet. Publish it and it appears in their list.',
    topicLabel: 'Topic',
    topicHint: 'What students and teachers filter the list by.',
    topicSaving: 'Saving…',
    shareHead: 'How students get in',
    shareCode: 'Class code',
    shareLink: 'Direct link',
    shareHint: 'Read the code out, or hand out the link. Either takes a student straight to this activity — they still see the consent notice first.',
    shareDraft: 'Both start working the moment you publish. Until then they say the activity is not open yet.',
    copyCode: 'Copy code',
    copyLink: 'Copy link',
    copied: 'Copied',
    openLink: 'Open it',
    questions: 'Questions',
    addQuestion: '+ Add question',
    newQuestion: 'New question',
    noQuestions: 'No questions yet. Write one, or upload a photo of one — either is enough.',
    uploadedNoText: 'Uploaded question — no text',
    picture: 'picture',
    moveUp: 'Move {code} up',
    moveDown: 'Move {code} down',
    edit: 'Edit',
    closeEdit: 'Close',
    danger: 'Danger zone',
    dangerHint: 'Deleting is refused once any student has worked on this. Close it to students instead — that stops new sessions and keeps every transcript readable.',
    deleteActivity: 'Delete this activity',
  },

  qform: {
    question: 'Question',
    placeholder: 'A recipe for four uses 300 g of flour. How much flour is needed for ten?',
    promptHint: 'Leave this empty if you are uploading the question as a picture instead.',
    orUpload: 'Or upload the question',
    imageHint: 'A photo or scan of the question. JPG, PNG or PDF, up to 10 MB.',
    needSomething: 'Write the question above, or upload a picture of it.',
    saveChanges: 'Save changes',
    add: 'Add question',
  },

  roster: {
    eyebrow: 'Reading',
    title: 'Student work',
    lede: 'One row per session. Open one to read it question by question, then send the useful exchanges through to labelling.',
    activity: 'Activity',
    empty: 'Nothing yet. Publish an activity and sessions appear here as students work through it.',
    thStudent: 'Student',
    thActivity: 'Activity',
    thStarted: 'Started',
    thQuestionsWithChat: 'Questions with chat',
    thMessages: 'Messages',
    thSnippets: 'Snippets',
    anonymous: 'anonymous',
    preview: 'your preview',
    signedInStudent: 'Signed-in student',
    read: 'Read',
  },

  transcript: {
    studentWork: 'Student work',
    back: 'back to student work',
    session: 'session',
    signedIn: 'Signed-in student',
    anon: 'Anonymous student',
    preview: 'Your own preview',
    started: 'Started {when}',
    consentVersion: 'consent v{version}',
    consentWaived: 'no consent record (staff preview)',
    prompt: 'prompt {version}',
    noPrompt: 'no prompt recorded',
    label: 'Label these exchanges',
    empty: 'This student opened the activity but never spoke to the tutor, so there is nothing to read.',
    ownQuestion: 'their own question',
    removedQuestion: 'This question has since been removed from the activity.',
    theirAnswer: 'Their answer',
    marked: 'Marked {earned}/{total}',
    selfMarked: 'they marked it “{mark}”',
    student: 'Student',
    tutor: 'Tutor',
    rated: 'rated {rating}',
  },

  labelling: {
    eyebrow: 'Building the dataset',
    title: 'Labelling',
    lede: 'Each card is one thing a student said and the reply that answered it. Keep the ones worth studying, then say which criteria the feedback meets and why.',
    show: 'Show',
    filterUndecided: 'Not yet decided',
    filterKept: 'Kept',
    filterDropped: 'Dropped',
    filterAll: 'Everything',
    oneSession: 'Filtered to one session.',
    showAll: 'Show every session',
    emptyUndecided: 'Nothing left to decide. Switch the filter to review what you kept.',
    emptyOther: 'No snippets match that filter.',
    studentAsked: 'Student asked',
    feedback: 'Feedback',
    studentRated: 'student rated it {rating}',
    keep: 'Keep for the dataset',
    drop: 'Drop',
    criteriaHead: 'Does this feedback…',
    why: 'Why',
    whyPlaceholder: 'Good nudge, stops short of the answer.',
    yes: 'Yes',
    partly: 'Partly',
    no: 'No',
  },

  prompt: {
    eyebrow: 'Tutor behaviour',
    title: 'AI prompt',
    lede: 'The instruction sitting behind every chat box in the system. Saving creates a new version and makes it current — nothing is overwritten.',
    warn: 'This applies to every activity and every teacher, not just yours. Sessions already recorded keep the version they ran on, so past data stays interpretable.',
    active: 'Currently active',
    setBy: 'set by {name}',
    none: 'None set. The tutor is running on its built-in behaviour until you write one.',
    newVersion: 'Write a new version',
    promptLabel: 'Prompt',
    promptPlaceholder: 'Never give the final answer. Ask one question back that moves the student one step closer.',
    noteLabel: 'What changed',
    notePlaceholder: 'More socratic, refuses worked examples before two attempts',
    saved: 'Saved. New sessions will use it from now on.',
    save: 'Save as new version',
    history: 'History',
    thVersion: 'Version',
    thSetBy: 'Set by',
    thWhen: 'When',
    thNote: 'Note',
  },

  admin: {
    eyebrow: 'Administrator',
    sections: 'Admin sections',
    people: 'People',
    teacherConsole: 'Teacher console →',
  },

  people: {
    eyebrow: 'Accounts',
    title: 'People',
    lede: 'There is no public sign-up. Accounts are created here, downwards through the hierarchy — an administrator adds managers and teachers, and a teacher adds their own students.',
    add: 'Add someone',
    role: 'Role',
    roleAdmin: 'administrator',
    roleManager: 'manager',
    roleTeacher: 'teacher',
    roleStudent: 'student',
    blurbAdmin: 'Everything, everywhere, including the dataset export.',
    blurbManager: 'Their teachers, and those teachers’ students and activities.',
    blurbTeacher: 'Their own students, their own activities, their own transcripts.',
    blurbStudent: 'Only themselves. Most students need no account — they work anonymously.',
    unassigned: 'Unassigned',
    pickParent: '— pick a {role} —',
    parentHintAdmin: 'May be left unassigned and set later.',
    parentHint: 'Which {parent} this {role} belongs to.',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    passwordHint: 'At least {min} characters. Shown so you can pass it on.',
    create: 'Create {role}',
    creating: 'Creating…',
    everyone: 'Everyone',
    thName: 'Name',
    thRole: 'Role',
    thEmail: 'Email',
    thReportsTo: 'Reports to',
    thLastSeen: 'Last seen',
    you: 'you',
    inactive: 'inactive',
    never: 'never',
    reset: 'Reset password',
    deactivate: 'Deactivate',
    reactivate: 'Reactivate',
    delete: 'Delete',
    created: 'Created {name}. Give them the password you just set.',
    resetPrompt: 'New password for {name}',
    resetDone: 'Password reset for {name}. They have been signed out everywhere.',
    nowActive: '{name} is now active.',
    nowInactive: '{name} is now inactive.',
    deleted: '{name} deleted.',
  },
}

const tr = {
  app: {
    loading: 'Yükleniyor',
  },

  common: {
    loading: 'Yükleniyor…',
    saving: 'Kaydediliyor…',
    cancel: 'İptal',
    back: 'Geri',
    remove: 'Kaldır',
    delete: 'Sil',
    optional: '(isteğe bağlı)',
    all: 'Tümü',
    dismiss: 'Kapat',
    questions_one: '{count} soru',
    questions_other: '{count} soru',
    words_one: '{count} kelime',
    words_other: '{count} kelime',
    strokes_one: '{count} çizgi',
    strokes_other: '{count} çizgi',
    files_one: '{count} dosya',
    files_other: '{count} dosya',
    events_one: '{count} olay',
    events_other: '{count} olay',
    criteria_one: '{count} ölçüt',
    criteria_other: '{count} ölçüt',
  },

  nav: {
    label: 'Gidilecek yer',
    home: 'Ana sayfa',
    signIn: 'Giriş yap',
    signOut: 'Çıkış yap',
    signingOut: 'Çıkılıyor…',
    myConsole: 'Konsolum',
    studentView: 'Öğrenci görünümü',
    joinWithCode: 'Sınıf kodu',
    language: 'Dil',
    signedInAs: '{name} olarak giriş yapıldı',
    working: 'Anonim çalışıyorsunuz',
  },

  topics: {
    label: 'Konu',
    all: 'Tüm konular',
    none: 'Konusuz',
    unset: '— konu yok —',
    ratio: 'Oran',
    'whole-numbers': 'Tam sayılar',
  },

  signin: {
    eyebrow: 'Hesabı olan öğretmenler ve öğrenciler',
    title: 'Giriş yap',
    email: 'E-posta',
    password: 'Şifre',
    submit: 'Giriş yap',
    busy: 'Giriş yapılıyor…',
    noAccount:
      'Hesabınız yok mu? Öğrenciler öğretmenlerinden aldıkları sınıf koduyla ya da listeden seçerek katılır.',
    startHere: 'Öğrenci olarak başla',
    staffAccounts: 'Öğretmen hesaplarını yönetici oluşturur.',
  },

  entry: {
    step: 'Adım {current} / {total}',

    consent: {
      eyebrow: 'Onay',
      title: 'Başlamadan önce',
      lede: 'Bu çalışma alanı, yapay zekâ geri bildiriminin öğrencilere problem çözmede nasıl yardımcı olduğunu inceleyen bir araştırmanın parçasıdır. Başlamadan önce lütfen bunu okuyun.',
      recordedHead: 'Neler kaydedilir',
      recorded1: 'Öğretmene yazdığınız her şey ve verdiği her yanıt.',
      recorded2: 'Cevaplarınız — yazılan, çizilen ya da yüklenen — ve aldıkları puanlar.',
      recorded3: 'Hangi soruları açtığınız, nasıl işaretlediğiniz ve ne zaman yaptığınız.',
      usedHead: 'Nasıl kullanılır',
      used1: 'Öğretimde yapay zekâ geri bildirimi araştırması için anonim bir veri kümesi oluşturmak üzere.',
      used2: 'Öğretmeniniz konuşmalarınızı okuyabilir ve çalışma için etiketleyebilir.',
      used3: 'Adınız, e-postanız veya okulunuz sorulmaz.',
      warn: 'Çalışma alanına adınızı, başka birinin adını veya başka bir kişisel bilgiyi yazmayın. Dilediğiniz an durabilir ve yaptığınız her şeyi çalışma alanının içinden silebilirsiniz.',
      agree: 'Bunu okudum; cevaplarımın ve konuşmalarımın bu araştırma için kaydedilmesini kabul ediyorum.',
      continue: 'Kabul et ve devam et',
      decline: 'Kabul etmiyorum',
    },

    declined: {
      eyebrow: 'Başlatılmadı',
      title: 'Hiçbir şey kaydedilmedi',
      lede: 'Çalışma alanı yalnızca onayla çalışır, bu yüzden burada yapılacak başka bir şey yok. Bu sekmeyi kapatabilirsiniz.',
      back: 'Onay formuna dön',
    },

    who: {
      title: 'Bugün nasıl çalışıyorsunuz?',
      lede: 'İkisi de olur. Olağan yol anonim çalışmaktır — hesap yalnızca öğretmeniniz size bir hesap açtıysa gerekir.',
      anon: 'Anonim devam et',
      anonMeta: 'Hesap yok. Hiçbir bilgi istenmez.',
      signIn: 'Giriş yap',
      signInMeta: 'Öğretmeniniz size e-posta ve şifre verdiyse.',
    },

    pick: {
      title: 'Ne üzerinde çalışıyorsunuz?',
      ledeSignedIn: 'Öğretmeniniz belirledi ve hesabınıza kaydedilir.',
      ledeAnon: 'Öğretmeninizin açmanızı söylediği etkinliği seçin. Anonim çalışıyorsunuz.',
      signedInAs: '{name} olarak giriş yaptınız. Yaptığınız her şey hesabınıza kaydedilir.',
      empty: 'Henüz açık bir etkinlik yok. Burada görünmesi için öğretmeninizin bir etkinlik yayımlaması gerekir.',
      noneInTopic: 'Bu konuda açık etkinlik yok. Başka bir konuyu ya da Tümü’nü deneyin.',
      enterCode: 'Sınıf kodu gir',
    },

    staff: {
      eyebrow: 'Öğretmen önizlemesi',
      notice:
        '{role} olarak giriş yaptınız; bu yüzden araştırma onay metni sizin için geçerli değil. Burada başlattığınız her şey öğrenci çalışması değil, önizleme olarak kaydedilir.',
    },
  },

  join: {
    eyebrow: 'Sınıf kodu',
    title: 'Sınıf koduyla katıl',
    lede: 'Öğretmeninizden aldığınız altı karakter. Harf ve rakamlardan oluşur; büyük ya da küçük yazmanız fark etmez.',
    label: 'Sınıf kodu',
    placeholder: 'ABC234',
    submit: 'Etkinliği bul',
    busy: 'Aranıyor…',
    found: 'Öğretmeniniz bunu verdi',
    start: 'Bu etkinliğe başla',
    starting: 'Başlatılıyor…',
    another: 'Başka bir kod dene',
    orList: 'Ya da listeden seç',
  },

  ws: {
    loading: 'Çalışmanız yükleniyor',
    cannotOpen: 'Bu oturum açılamıyor',
    startAgain: 'Yeniden başla',
    questionsFallback: 'Sorularınız',
    ownQuestions: 'Kendi sorularınız',
    markedLine: '{code} değerlendirildi — {total} üzerinden {earned}.',
    fullMarks: 'Tam puan.',
    handMarked: '{code} elle değerlendirilmek üzere öğretmeninizde. Bir çizimi ya da fotoğrafı puanlayamam.',
    confirmWithdraw: 'Bu oturumdaki her şey silinsin mi? Bu geri alınamaz.',
    tabQuestions: 'Sorular',
    tabProblem: 'Soru',
    tabTutor: 'Öğretmen',
    showQuestions: 'Soruları göster',
    showTutor: 'Öğretmeni göster',
    showTutorUnread: 'Öğretmeni göster, yeni yanıt var',
    newReply: 'Yeni yanıt',
    switchPanel: 'Paneli değiştir',
    questionSet: 'Soru listesi',
    tutorPane: 'Yapay zekâ öğretmeni',
    closeTutor: 'Öğretmeni kapat',
  },

  ql: {
    hide: 'Soruları gizle',
    tally: '{total} sorudan {done}',
    tallyLabel: 'tamamlandı olarak işaretlendi',
    withTeacher: 'Öğretmeninizde',
    markedScore: '{mark} · {earned}/{total}',
    pictureQuestion: 'Soru bir görsel',
    askOwn: 'Kendi sorunu sor',
    ownLabel: 'Kendi sorunuz',
    ownPlaceholder: 'Başka bir yerde mi takıldınız? O soruyu buraya yazın ve öğretmenle üzerinde çalışın.',
    ownAdd: 'Listeme ekle',
    points: '{count} puan',
    withdraw: 'Yaptığım her şeyi sil',
  },

  qp: {
    marks: '{count} puan',
    questionOf: 'Soru {current} / {total}',
    tutor: 'Öğretmen',
    questionAsSet: 'Sorunun kendisi',
    question: 'Soru',
    yourAnswer: 'Cevabınız',
    howToAnswer: 'Nasıl cevaplanacak',
    modeWarn: '{mode} seçeneğine geçmek {what} siler.',
    discardSwitch: 'Sil ve geç',
    keepAnswer: 'Cevabımı koru',
    writtenAnswer: 'Yazılı cevabınız',
    placeholderMarkable: 'Cevabınızı buraya yazın. Öğretmen bunu bir örnek cevaba göre değil, ölçütlere göre değerlendirir.',
    placeholderUnmarked: 'Şimdiye kadar ne denediğinizi yazın; öğretmen üzerinden birlikte geçecek.',
    workingNudge: 'Bu soru genelde elle çözülür — Çiz ya da Yükle daha uygun olabilir.',
    boardAlt: 'Şimdiye kadarki tahtanız',
    editBoard: 'Tahtanızı düzenleyin',
    drawBoard: 'Tahtaya çizin',
    boardMeta: '{strokes} · {size} olarak kaydedildi',
    boardHint: 'Kareli kâğıt · kalem, silgi, geri al',
    aPng: 'PNG',
    addFile: 'Fotoğraf ya da dosya ekle',
    addFileMeta: 'Buraya bırakın ya da yapıştırın · JPG, PNG veya PDF · 10 MB',
    rejected: 'Eklenmedi: {list}. Dosyayı düzeltip yeniden ekleyin.',
    openInTab: '{name} dosyasını yeni sekmede aç',
    check: 'Cevabımı kontrol et',
    hint: 'İpucu al',
    stale: 'Değerlendirildikten sonra değiştirildi — yeniden kontrol edin.',
    howDidItGo: 'Bu soru nasıl gitti?',
    withTeacher: 'Öğretmeninizde',
    nothingToMark: 'Değerlendirilecek bir şey yok',
    doThisNext: 'Sırada bunu yap',
    previous: 'Önceki',
    next: 'Sonraki',
    discardWrite_one: 'yazdığınız cevabı ({count} kelime)',
    discardWrite_other: 'yazdığınız cevabı ({count} kelime)',
    discardDraw_one: 'tahtanızı ({count} çizgi)',
    discardDraw_other: 'tahtanızı ({count} çizgi)',
    discardUpload_one: 'yüklediğiniz {count} dosyayı',
    discardUpload_other: 'yüklediğiniz {count} dosyayı',
  },

  tp: {
    tutor: 'Öğretmen',
    workingOn: 'Üzerinde çalışılan',
    hide: 'Öğretmeni gizle',
    close: 'Kapat',
    hintAction: 'Bana ipucu ver',
    conceptAction: 'Konuyu açıkla',
    exampleAction: 'Çözümlü örnek',
    reviewAction: 'Akıl yürütmemi kontrol et',
    helpful: 'Yararlı olarak işaretlendi',
    notHelpful: 'Yararsız olarak işaretlendi',
    didThisHelp: 'Bu yardımcı oldu mu?',
    yes: 'Evet',
    no: 'Hayır',
    writing: 'Öğretmen yazıyor',
    messageLabel: 'Öğretmene mesaj yaz',
    placeholder: 'Bu soru hakkında sorun…',
    send: 'Gönder',
  },

  wb: {
    title: 'Tahta',
    forQuestion: '{code} için tahta',
    workingOn: 'Üzerinde çalışılan',
    penColour: 'Kalem rengi',
    erase: 'Sil',
    undo: 'Geri al',
    clear: 'Temizle',
    rotate: 'Yazmak için daha fazla yer açmak üzere telefonunuzu yatay çevirin.',
    canvasLabel: 'Çizim alanı. Klavyeyle çizim desteklenmiyor — bunun yerine çözümünüzün fotoğrafını ekleyin.',
    strokesSaved: '{strokes} · cevabınızla birlikte PNG olarak kaydedilir',
    drawHint: 'Fare, parmak ya da kalemle çizin',
    save: 'Cevaba kaydet',
    inkGraphite: 'Kurşun kalem',
    inkTeal: 'Yeşil kalem',
    inkRed: 'Kırmızı kalem',
  },

  marks: {
    newLabel: 'Başlanmadı',
    newShort: 'Yeni',
    draftLabel: 'Yazıldı, kontrol edilmedi',
    draftShort: 'Taslak',
    reviseLabel: 'Gözden geçirilmeli',
    reviseShort: 'Gözden geçir',
    masteredLabel: 'Tam',
    masteredShort: 'Tam',
    doneLabel: 'Bitti',
    doneShort: 'Bitti',
    unfinishedLabel: 'Bitmedi',
    unfinishedShort: 'Bitmedi',
    wrongLabel: 'Yanlış yaptım',
    wrongShort: 'Yanlış',
  },

  modes: {
    writeLabel: 'Yaz',
    writeHint: 'Cevabınızı yazın',
    drawLabel: 'Çiz',
    drawHint: 'Tahta',
    uploadLabel: 'Yükle',
    uploadHint: 'Fotoğraf ya da PDF',
  },

  teacher: {
    eyebrow: 'Öğretmen',
    sections: 'Öğretmen bölümleri',
    activities: 'Etkinlikler',
    studentWork: 'Öğrenci çalışmaları',
    labelling: 'Etiketleme',
    prompt: 'YZ yönergesi',
    accounts: 'Hesaplar →',
  },

  activities: {
    eyebrow: 'Hazırlama',
    title: 'Etkinlikler',
    lede: 'Etkinlik bir soru kümesidir. Onu öğrencilerin önüne koyan şey yayımlamaktır — siteyi açar ya da sınıf kodunu yazar, onay metnini kabul eder ve başlarlar. Öğretmene söyledikleri her şey bu etkinliğe kaydedilir.',
    new: 'Yeni etkinlik',
    titleLabel: 'Başlık',
    titlePlaceholder: 'Bir hesabı üç kişiye bölmek',
    blurbLabel: 'Kısa açıklama',
    blurbPlaceholder: 'Bir niceliği verilen oranda paylaştırma ve toplamı kontrol etme.',
    create: 'Etkinlik oluştur',
    creating: 'Oluşturuluyor…',
    scopeAll: 'Sistemdeki her şey',
    scopeOwn: 'Sizin etkinlikleriniz',
    empty: 'Henüz yok. Yukarıdan bir etkinlik oluşturun, bir iki soru ekleyin, sonra yayımlayın ki öğrenciler görebilsin.',
    noneInTopic: 'Bu konuda henüz etkinlik yok.',
    open: 'Açık',
    draft: 'Taslak',
    filterLabel: 'Konuya göre süz',
  },

  editor: {
    breadcrumb: 'Etkinlikler',
    seeWork: 'Çalışmalarını gör',
    publish: 'Yayımla',
    closeToStudents: 'Öğrencilere kapat',
    openHead: 'Öğrencilere açık',
    openHint: 'Öğrenciler siteyi açtığında gördükleri listede yer alır ve sınıf kodu çalışır. Onu açan şey yayımlamaktır; ders bitince yeniden kapatın.',
    draftHead: 'Henüz açık değil',
    draftHintEmpty: 'Öğrenciler bunu göremez. En az bir soru ekleyin, sonra yayımlayın.',
    draftHint: 'Öğrenciler bunu henüz göremez. Yayımlayın ve listelerinde görünsün.',
    topicLabel: 'Konu',
    topicHint: 'Öğrencilerin ve öğretmenlerin listeyi süzdüğü ölçüt.',
    topicSaving: 'Kaydediliyor…',
    shareHead: 'Öğrenciler nasıl girer',
    shareCode: 'Sınıf kodu',
    shareLink: 'Doğrudan bağlantı',
    shareHint: 'Kodu okuyun ya da bağlantıyı paylaşın. İkisi de öğrenciyi doğrudan bu etkinliğe götürür — yine de önce onay metnini görürler.',
    shareDraft: 'İkisi de yayımladığınız anda çalışmaya başlar. O zamana kadar etkinliğin açık olmadığını söylerler.',
    copyCode: 'Kodu kopyala',
    copyLink: 'Bağlantıyı kopyala',
    copied: 'Kopyalandı',
    openLink: 'Aç',
    questions: 'Sorular',
    addQuestion: '+ Soru ekle',
    newQuestion: 'Yeni soru',
    noQuestions: 'Henüz soru yok. Bir soru yazın ya da fotoğrafını yükleyin — ikisi de yeterli.',
    uploadedNoText: 'Yüklenmiş soru — metin yok',
    picture: 'görsel',
    moveUp: '{code} sorusunu yukarı taşı',
    moveDown: '{code} sorusunu aşağı taşı',
    edit: 'Düzenle',
    closeEdit: 'Kapat',
    danger: 'Dikkat gerektiren işlemler',
    dangerHint: 'Bir öğrenci bu etkinlik üzerinde çalıştıktan sonra silme reddedilir. Bunun yerine öğrencilere kapatın — bu yeni oturumları durdurur ve tüm kayıtları okunabilir bırakır.',
    deleteActivity: 'Bu etkinliği sil',
  },

  qform: {
    question: 'Soru',
    placeholder: 'Dört kişilik bir tarifte 300 g un kullanılıyor. On kişi için ne kadar un gerekir?',
    promptHint: 'Soruyu görsel olarak yükleyecekseniz burayı boş bırakın.',
    orUpload: 'Ya da soruyu yükleyin',
    imageHint: 'Sorunun fotoğrafı ya da taraması. JPG, PNG veya PDF, en fazla 10 MB.',
    needSomething: 'Yukarıya soruyu yazın ya da bir görselini yükleyin.',
    saveChanges: 'Değişiklikleri kaydet',
    add: 'Soru ekle',
  },

  roster: {
    eyebrow: 'Okuma',
    title: 'Öğrenci çalışmaları',
    lede: 'Her satır bir oturum. Soru soru okumak için birini açın, sonra işe yarar alışverişleri etiketlemeye gönderin.',
    activity: 'Etkinlik',
    empty: 'Henüz yok. Bir etkinlik yayımlayın; öğrenciler üzerinde çalıştıkça oturumlar burada görünür.',
    thStudent: 'Öğrenci',
    thActivity: 'Etkinlik',
    thStarted: 'Başlangıç',
    thQuestionsWithChat: 'Sohbetli soru',
    thMessages: 'Mesaj',
    thSnippets: 'Kesit',
    anonymous: 'anonim',
    preview: 'önizlemeniz',
    signedInStudent: 'Girişli öğrenci',
    read: 'Oku',
  },

  transcript: {
    studentWork: 'Öğrenci çalışmaları',
    back: 'öğrenci çalışmalarına dön',
    session: 'oturum',
    signedIn: 'Girişli öğrenci',
    anon: 'Anonim öğrenci',
    preview: 'Kendi önizlemeniz',
    started: 'Başlangıç {when}',
    consentVersion: 'onay s{version}',
    consentWaived: 'onay kaydı yok (öğretmen önizlemesi)',
    prompt: 'yönerge {version}',
    noPrompt: 'yönerge kaydı yok',
    label: 'Bu alışverişleri etiketle',
    empty: 'Bu öğrenci etkinliği açtı ama öğretmenle hiç konuşmadı, dolayısıyla okunacak bir şey yok.',
    ownQuestion: 'kendi sorusu',
    removedQuestion: 'Bu soru o zamandan beri etkinlikten çıkarıldı.',
    theirAnswer: 'Cevabı',
    marked: '{total} üzerinden {earned}',
    selfMarked: 'kendisi “{mark}” olarak işaretledi',
    student: 'Öğrenci',
    tutor: 'Öğretmen',
    rated: '{rating} olarak değerlendirdi',
  },

  labelling: {
    eyebrow: 'Veri kümesini oluşturma',
    title: 'Etiketleme',
    lede: 'Her kart, bir öğrencinin söylediği bir şey ve ona verilen yanıttır. İncelemeye değer olanları tutun, sonra geri bildirimin hangi ölçütleri karşıladığını ve nedenini yazın.',
    show: 'Göster',
    filterUndecided: 'Henüz karar verilmedi',
    filterKept: 'Tutulanlar',
    filterDropped: 'Çıkarılanlar',
    filterAll: 'Her şey',
    oneSession: 'Tek bir oturuma süzüldü.',
    showAll: 'Tüm oturumları göster',
    emptyUndecided: 'Karar verilecek bir şey kalmadı. Tuttuklarınızı gözden geçirmek için süzgeci değiştirin.',
    emptyOther: 'Bu süzgece uyan kesit yok.',
    studentAsked: 'Öğrenci sordu',
    feedback: 'Geri bildirim',
    studentRated: 'öğrenci {rating} olarak değerlendirdi',
    keep: 'Veri kümesinde tut',
    drop: 'Çıkar',
    criteriaHead: 'Bu geri bildirim…',
    why: 'Neden',
    whyPlaceholder: 'İyi bir yönlendirme, cevabı vermeden duruyor.',
    yes: 'Evet',
    partly: 'Kısmen',
    no: 'Hayır',
  },

  prompt: {
    eyebrow: 'Öğretmen davranışı',
    title: 'YZ yönergesi',
    lede: 'Sistemdeki her sohbet kutusunun arkasındaki yönerge. Kaydetmek yeni bir sürüm oluşturur ve onu geçerli yapar — hiçbir şeyin üzerine yazılmaz.',
    warn: 'Bu yalnızca sizin değil, her etkinlik ve her öğretmen için geçerlidir. Kaydedilmiş oturumlar çalıştıkları sürümü korur, böylece eski veriler yorumlanabilir kalır.',
    active: 'Şu anda geçerli',
    setBy: '{name} tarafından ayarlandı',
    none: 'Ayarlanmadı. Siz bir yönerge yazana kadar öğretmen yerleşik davranışıyla çalışır.',
    newVersion: 'Yeni bir sürüm yaz',
    promptLabel: 'Yönerge',
    promptPlaceholder: 'Nihai cevabı asla verme. Öğrenciyi bir adım yaklaştıracak tek bir soru sor.',
    noteLabel: 'Ne değişti',
    notePlaceholder: 'Daha sokratik, iki denemeden önce çözümlü örnek vermiyor',
    saved: 'Kaydedildi. Yeni oturumlar bundan sonra bunu kullanacak.',
    save: 'Yeni sürüm olarak kaydet',
    history: 'Geçmiş',
    thVersion: 'Sürüm',
    thSetBy: 'Ayarlayan',
    thWhen: 'Tarih',
    thNote: 'Not',
  },

  admin: {
    eyebrow: 'Yönetici',
    sections: 'Yönetici bölümleri',
    people: 'Kişiler',
    teacherConsole: 'Öğretmen konsolu →',
  },

  people: {
    eyebrow: 'Hesaplar',
    title: 'Kişiler',
    lede: 'Herkese açık kayıt yoktur. Hesaplar burada, hiyerarşide aşağı doğru oluşturulur — yönetici müdür ve öğretmen ekler, öğretmen de kendi öğrencilerini ekler.',
    add: 'Kişi ekle',
    role: 'Rol',
    roleAdmin: 'yönetici',
    roleManager: 'müdür',
    roleTeacher: 'öğretmen',
    roleStudent: 'öğrenci',
    blurbAdmin: 'Her yerde her şey, veri kümesi aktarımı dâhil.',
    blurbManager: 'Kendi öğretmenleri ve o öğretmenlerin öğrencileri ile etkinlikleri.',
    blurbTeacher: 'Kendi öğrencileri, kendi etkinlikleri, kendi kayıtları.',
    blurbStudent: 'Yalnızca kendisi. Öğrencilerin çoğuna hesap gerekmez — anonim çalışırlar.',
    unassigned: 'Atanmadı',
    pickParent: '— bir {role} seçin —',
    parentHintAdmin: 'Atanmamış bırakılabilir, sonra ayarlanır.',
    parentHint: 'Bu {role} hangi {parent} kişisine bağlı.',
    name: 'Ad',
    email: 'E-posta',
    password: 'Şifre',
    passwordHint: 'En az {min} karakter. İletebilmeniz için görünür bırakılır.',
    create: '{role} oluştur',
    creating: 'Oluşturuluyor…',
    everyone: 'Herkes',
    thName: 'Ad',
    thRole: 'Rol',
    thEmail: 'E-posta',
    thReportsTo: 'Bağlı olduğu',
    thLastSeen: 'Son görülme',
    you: 'siz',
    inactive: 'pasif',
    never: 'hiç',
    reset: 'Şifreyi sıfırla',
    deactivate: 'Pasifleştir',
    reactivate: 'Yeniden etkinleştir',
    delete: 'Sil',
    created: '{name} oluşturuldu. Belirlediğiniz şifreyi kendisine verin.',
    resetPrompt: '{name} için yeni şifre',
    resetDone: '{name} için şifre sıfırlandı. Her yerdeki oturumları kapatıldı.',
    nowActive: '{name} artık etkin.',
    nowInactive: '{name} artık pasif.',
    deleted: '{name} silindi.',
  },
}

export const DICTIONARIES = { en, tr }
